# Generated by Django 5.1.4 on 2025-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveillance_system', models.BooleanField(blank=True, default=False, null=True)),
                ('intrusion_detection', models.BooleanField(blank=True, default=False, null=True)),
                ('counter_surveillance', models.BooleanField(blank=True, default=False, null=True)),
                ('security_consultancy_and_raining', models.BooleanField(blank=True, default=False, null=True)),
                ('investigation_and_recovery', models.BooleanField(blank=True, default=False, null=True)),
                ('gadgets_and_accessories', models.BooleanField(blank=True, default=False, null=True)),
                ('additional_info', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('preference_date', models.CharField(max_length=100)),
                ('preference_time', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
