# Generated by Django 5.1.4 on 2025-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=250)),
                ('image', models.ImageField(default='blog_img', upload_to='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='counter_surveillance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='gadgets_and_accessories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='intrusion_detection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='investigation_and_recovery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='security_consultancy_and_raining',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='surveillance_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
